#ifndef MOUSEBUTTONCODES_H
#define MOUSEBUTTONCODES_H

// From glfw3.h
#define GGE_MOUSE_BUTTON_1         0
#define GGE_MOUSE_BUTTON_2         1
#define GGE_MOUSE_BUTTON_3         2
#define GGE_MOUSE_BUTTON_4         3
#define GGE_MOUSE_BUTTON_5         4
#define GGE_MOUSE_BUTTON_6         5
#define GGE_MOUSE_BUTTON_7         6
#define GGE_MOUSE_BUTTON_8         7
#define GGE_MOUSE_BUTTON_LAST      GGE_MOUSE_BUTTON_8
#define GGE_MOUSE_BUTTON_LEFT      GGE_MOUSE_BUTTON_1
#define GGE_MOUSE_BUTTON_RIGHT     GGE_MOUSE_BUTTON_2
#define GGE_MOUSE_BUTTON_MIDDLE    GGE_MOUSE_BUTTON_3

#endif // MOUSEBUTTONCODES_H
